# Generated by Django 6.0.2 on 2026-03-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images/'),
        ),
    ]
