# Generated by Django 6.0.2 on 2026-03-03 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_contactrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
