# Generated by Django 6.0.2 on 2026-03-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_contactrequest_service_contactrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
