# Generated by Django 6.0.2 on 2026-03-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_contactrequest_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
