# Generated by Django 6.0.2 on 2026-03-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_contactrequest_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('diagnostico', 'En diagnóstico'), ('proceso', 'En reparación'), ('espera', 'Esperando repuesto'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
